name: test error

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  setup-chrome-rd:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 1 - 
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile "chrome_setup.exe"
          Start-Process "chrome_setup.exe" -ArgumentList "/silent /install" -NoNewWindow

      - name: 2 - 
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chrome_remote_desktop_host.msi"
          Start-Process "msiexec.exe" -ArgumentList "/i", "chrome_remote_desktop_host.msi", "/quiet" -NoNewWindow

      - name: 2.5 
        run: |
          Start-Process ".\BlueStacksInstaller_5.22.100.1024_native_1c52247a23e7bc367e286417a4deab16_MTsxNQ==.exe" -ArgumentList "--defaultImageName", "Nougat64", "--imageToLaunch", "Nougat64" -NoNewWindow

      - name: 3 - 
        run: |
          & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AVMBsJj3j9TBYJvyZlFYWYVX5J4nFk_VomjSq9FKQIZjhv1B8EdWmNy3yUicBKsS5poMkg" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=111111
